packages:
  - 'packages/**'

# Define a catalog of version ranges.
catalog:
  cross-env: ^10.1.0
  immutable: ^5.1.9
  native-copyfiles: ^2.0.3
  remove-glob: ^1.2.1
  sass: ^1.101.0
  typescript: ^7.0.2

minimumReleaseAge: 2880 # 2 days in minutes

minimumReleaseAgeExclude:
  # exclude packages that I personally maintain and are safe to use on the same day
  - '@lerna-lite/*'
