packages:
  - 'packages/**'

allowBuilds:
  '@parcel/watcher': false
  esbuild: false

# Define a catalog of version ranges.
catalog:
  cross-env: ^10.1.0
  native-copyfiles: ^2.0.3
  remove-glob: ^1.2.1
  sass: ^1.102.0
  typescript: ^7.0.2

minimumReleaseAge: 2880 # 2 days in minutes

minimumReleaseAgeExclude:
  # exclude packages that I personally maintain and are safe to use on the same day
  - '@lerna-lite/*'

overrides:
  ip-address: ^10.4.0
  undici: ^8.10.0