name: Clear notifications (bash)

on:
  workflow_dispatch:   # run manually from the Actions UI

jobs:
  clear:
    runs-on: ubuntu-latest          # <-- Linux runner
    steps:
      - name: Mark all notifications as read
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/notifications
